Thaumcraft trees fast leaf decay
GTNewHorizons/Random-Things pull request #6
Opened 2024-04-17 07:33 UTC by HoleFish

2024-04-17 08:17 UTC, Dream-Master commented
10 years later….. nice want this for ages 😎

2024-04-17 08:26 UTC, Ethryan commented
Can’t this be called a patch instead of a new feature?

2024-04-17 08:39 UTC, Dream-Master commented
it is a fix indeed

2024-04-17 08:44 UTC, chochem commented
![image](https://github.com/GTNewHorizons/Random-Things/assets/40274384/c985d816-c086-4ebe-ab50-8b3628726b21)
XD

2024-04-17 08:45 UTC, eigenraven requested changes

2024-04-17 08:45 UTC, eigenraven commented on src/main/java/lumien/randomthings/Mixins/Mixin.java
> +    BLOCK_MAGICAL_LEAVES("MixinBlockMagicalLeaves", Side.BOTH, () -> VanillaChanges.FASTER_LEAVEDECAY),
This needs a check for thaumcraft, otherwise this will break when running without tc installed with strict mixin validation options. See how Hodgepodge/Angelica do it

2024-04-17 09:02 UTC, HoleFish commented on src/main/java/lumien/randomthings/Mixins/Mixin.java
> +    BLOCK_MAGICAL_LEAVES("MixinBlockMagicalLeaves", Side.BOTH, () -> VanillaChanges.FASTER_LEAVEDECAY),
Forgot to read doc :(

2024-04-17 12:08 UTC, HoleFish commented on src/main/java/lumien/randomthings/Mixins/Mixin.java
> +    BLOCK_MAGICAL_LEAVES("MixinBlockMagicalLeaves", Side.BOTH, () -> VanillaChanges.FASTER_LEAVEDECAY),
copied everything from them...

2024-04-27 15:17 UTC, eigenraven approved these changes

2024-04-27 16:46 UTC, merged